version: '2.1'

services:


  pocket-core-testnet:
    image: poktnetwork/pocket-core:${ENV:-staging-latest}

    privileged: true
    command: "pocket start --seeds f31f77c8a882504ef8525e6557351295107f1680@10.20.4.109:26656 --blockTime=1"
    build: ../../docker
    expose:
      - "8081"  #  POKT RPC
      - "26657" #  Tendermint RPC
      - "26656" #  Tendermint Peers
      - "46656" #  Tendermint Peers
    environment:
      POCKET_CORE_KEY: "b8a56dead392e2b57eaba988068d0cedc0a11b9a16ca9610b094ec31a9cbc06650220553e5ccf56a863eaed88ebf1487e1dcb20e7fffbe0fb841cab1bb76af4d"
      POCKET_CORE_PASSPHRASE: "yo"

    volumes:
        - "./chains.json:/home/app/.pocket/chains.json"
        - "./genesis.json:/home/app/.pocket/genesis.json"
    networks:
      - pocket

  nginx:
    image: poktnetwork/nginx:pocket-core
    build: . 
    ports:
      - "8081:8081"
      - "26657:26657"
      - "26656:26656"
    volumes:
      - "./conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    environment:
      HOST: "0.0.0.0"

    networks:
      - pocket

networks:
  pocket:
    driver: bridge
